// <auto-generated />
using System;
using BookletApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookletApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookletApi.Models.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("BookletApi.Models.SectionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionTranslations");
                });

            modelBuilder.Entity("BookletApi.Models.UniversityInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutUniversity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeSpecialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColloquiumAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Concepts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Credits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisciplineProcedure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisciplineResp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Encouragement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExamRules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExchangePrograms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpulsionCases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneralTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndividualCurriculum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstitutionExpulsion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LectureAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LibraryRightsDuties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LibraryServiceRules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PracticalCriteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PracticalTasks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PracticeOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadersRightsDuties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reinstatement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReprimandCases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RightsDuties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scholarships")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeminarLabAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SevereReprimandCases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialSupport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentLoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentOrientedSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummerSemester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemporarySuspension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TheoreticalCriteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WarningCases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UniversityInfos");
                });

            modelBuilder.Entity("BookletApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookletApi.Models.SectionTranslation", b =>
                {
                    b.HasOne("BookletApi.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });
#pragma warning restore 612, 618
        }
    }
}
